#!/bin/bash

#  abs path to setup, change pwd
directory=$(dirname $0);
cd "$directory" || exit ;

# environment
python3 -m venv venv || exit ;
source venv/bin/activate || exit ;
pip3 install -r requirements.txt || exit;

# Django configure
cd root || exit;
python3 manage.py migrate;
python3 manage.py collectstatic;
cd ..;


echo "Configure etc";

