#!/bin/bash

sudo apt-get update;
sudo apt-get upgrade;

sudo apt-get install git-all;
sudo apt-get install snapd
sudo apt-get install python3-pip apache2 libapache2-mod-wsgi-py3;
sudo apt-get install python3-venv;

# CertBot
sudo snap install core;
sudo snap refresh core;
sudo snap install --classic certbot;
sudo ln -s /snap/bin/certbot /usr/bin/certbot;

#  abs path to setup, change pwd
directory=$(dirname $0);
cd "$directory" || exit ;

# environment
python3 -m venv venv || exit ;
source venv/bin/activate || exit ;
pip3 install -r requirements.txt || exit;

# Django configure
cd root || exit;
python3 manage.py migrate;
python3 manage.py collectstatic;
cd ..;

chmod 664 ./database.sqlite3;
sudo chown :www-data ./database.sqlite3;
sudo chown :www-data ./

echo "Configure etc";

