#!/bin/bash
directory=$(dirname $0);
cd "$directory" || exit ;

git fetch origin main || exit;
git reset --hard origin/main || exit;

# environment
source venv/bin/activate || exit ;
pip3 install -r requirements.txt || exit;

# Django configure
cd root || exit;
python3 manage.py migrate;
python3 manage.py collectstatic --noinput;
cd ..;

# restart apache2
sudo systemctl restart apache2;  # its if you have apache2
